package:
  format-version: "1.0.0"
  name: "crypto-hsm"
  type: "application"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.14.0"
